[[constraint]]
  name = "github.com/machinebox/sdk-go"
  version = "0.2.0"

[[constraint]]
  name = "github.com/gocraft/web"
  version = "v1.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "v1.0.4"

[[constraint]]
  name = "github.com/mattn/go-sqlite3"
  version = "v1.6.0"

[[constraint]]
  name = "github.com/nlopes/slack"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "google.golang.org/api"

[[constraint]]
  name = "cloud.google.com/go"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "github.com/disintegration/imaging"
  version = "1.3.0"
